server:
  port: 8666
  error:
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

spring:
  profiles:
    active: dev
  application:
    name: users-managed
  data:
    mongodb:
      authentication-database: admin
      uri: ${SPRING_DATASOURCE_URL:mongodb://localhost:27017/UsersDB}
      auto-index-creation: true
