version: '2'

services:
  app:
    image:  'ghcr.io/lovkachebasher/spring-thymeleaf-crud/spring-thymeleaf-crud'
    ports:
      - '8666:8666'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=mongodb://db:27017/UsersDB

  db:
    image: 'mongo'
    container_name: db